### ISSUE TITLE
Question on `pickle` usage

### ISSUE THREAD

**Issue by rgieseke** [pik-primap/climate_categories#37]
Hi Mika,

i was wondering whether you had considered using generated `py` modules instead of `pickle` files.
The security concerns raised with regards to `pickle` likely don't apply here, but i have used the approach of generating  Python code from data in a few projects.

**Comment by rgieseke** [comment]
Some considerations for me would be
- a general reluctance to put binary files into Git
- being able to see in a diff what's changed (and being sure it's the same change as in the YAML file)
- being able to inspect/see the code without loading it
- one thing less to learn/think about for potential contributors

**Comment by mikapfl** [comment]
I agree with those advantages. I see the following disadvantages:

* non-binary files look like they can be changed by humans, but those can't (probably solvable with a disclaimer at the top)
* added complexity

Probably, if both options were available, I'd choose generated python code.

At the moment, we already have the `from_spec` and `to_spec` machinery, which probably could do the heavy lifting. However, off the top of my head I'm not sure if `from_spec` is fast enough (it does some validation which might be slow).
